# Generated by Django 6.0.2 on 2026-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Conserje', 'Conserje'), ('Administrador', 'Administrador')], max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('Agregar usuario', 'Agregar usuario'), ('Eliminar usuario', 'Eliminar usuario'), ('Soporte técnico', 'Soporte técnico'), ('Solicitud de capacitación', 'Solicitud de capacitación'), ('Otra', 'Otra')], max_length=50)),
                ('tipo_accion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En revisión', 'En revisión'), ('En proceso', 'En proceso'), ('En espera de información', 'En espera de información'), ('Cerrado', 'Cerrado')], default='Recibido', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
