# Generated by Django 6.0.2 on 2026-02-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='edificio',
            field=models.CharField(choices=[('Edificio Central - Av. Providencia 1234', 'Edificio Central - Av. Providencia 1234'), ('Torre Norte - Apoquindo 4567', 'Torre Norte - Apoquindo 4567'), ('Condominio Los Pinos - Las Condes 789', 'Condominio Los Pinos - Las Condes 789')], default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_accion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
