# Generated by Django 6.0.2 on 2026-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_edificio_alter_ticket_tipo_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='edificio',
            field=models.CharField(max_length=200),
        ),
    ]
